rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

before_script:
  - "mysql -e 'create database woo_test;'"
  - "psql -c 'create database woo_test;' -U postgres"
  - "cp config/database.yml.example config/database.yml"
