require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnquiriesController do

  # This should return the minimal set of attributes required to create a valid
  # Enquiry. As you add validations to Enquiry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all Enquiries as @Enquiries" do
      Enquiry = Enquiry.create! valid_attributes
      get :index
      assigns(:Enquiries).should eq([Enquiry])
    end
  end

  describe "GET show" do
    it "assigns the requested Enquiry as @Enquiry" do
      Enquiry = Enquiry.create! valid_attributes
      get :show, :id => Enquiry.id.to_s
      assigns(:Enquiry).should eq(Enquiry)
    end
  end

  describe "GET new" do
    it "assigns a new Enquiry as @Enquiry" do
      get :new
      assigns(:Enquiry).should be_a_new(Enquiry)
    end
  end

  describe "GET edit" do
    it "assigns the requested Enquiry as @Enquiry" do
      Enquiry = Enquiry.create! valid_attributes
      get :edit, :id => Enquiry.id.to_s
      assigns(:Enquiry).should eq(Enquiry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Enquiry" do
        expect {
          post :create, :Enquiry => valid_attributes
        }.to change(Enquiry, :count).by(1)
      end

      it "assigns a newly created Enquiry as @Enquiry" do
        post :create, :Enquiry => valid_attributes
        assigns(:Enquiry).should be_a(Enquiry)
        assigns(:Enquiry).should be_persisted
      end

      it "redirects to the created Enquiry" do
        post :create, :Enquiry => valid_attributes
        response.should redirect_to(Enquiry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved Enquiry as @Enquiry" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enquiry.any_instance.stub(:save).and_return(false)
        post :create, :Enquiry => {}
        assigns(:Enquiry).should be_a_new(Enquiry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enquiry.any_instance.stub(:save).and_return(false)
        post :create, :Enquiry => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested Enquiry" do
        Enquiry = Enquiry.create! valid_attributes
        # Assuming there are no other Enquiries in the database, this
        # specifies that the Enquiry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Enquiry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => Enquiry.id, :Enquiry => {'these' => 'params'}
      end

      it "assigns the requested Enquiry as @Enquiry" do
        Enquiry = Enquiry.create! valid_attributes
        put :update, :id => Enquiry.id, :Enquiry => valid_attributes
        assigns(:Enquiry).should eq(Enquiry)
      end

      it "redirects to the Enquiry" do
        Enquiry = Enquiry.create! valid_attributes
        put :update, :id => Enquiry.id, :Enquiry => valid_attributes
        response.should redirect_to(Enquiry)
      end
    end

    describe "with invalid params" do
      it "assigns the Enquiry as @Enquiry" do
        Enquiry = Enquiry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enquiry.any_instance.stub(:save).and_return(false)
        put :update, :id => Enquiry.id.to_s, :Enquiry => {}
        assigns(:Enquiry).should eq(Enquiry)
      end

      it "re-renders the 'edit' template" do
        Enquiry = Enquiry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enquiry.any_instance.stub(:save).and_return(false)
        put :update, :id => Enquiry.id.to_s, :Enquiry => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested Enquiry" do
      Enquiry = Enquiry.create! valid_attributes
      expect {
        delete :destroy, :id => Enquiry.id.to_s
      }.to change(Enquiry, :count).by(-1)
    end

    it "redirects to the Enquiries list" do
      Enquiry = Enquiry.create! valid_attributes
      delete :destroy, :id => Enquiry.id.to_s
      response.should redirect_to(Enquiries_url)
    end
  end

end
